---
- hosts: all
  become: true
  tasks:
     - name: Upgrade all installed packages for CentOS
       yum:
         name: "*"
         state: latest
         update_cache: yes
       when: ansible_distribution == "CentOS"



     - name: Upgrade all installed packages for CentOS
       apt:
         name: "*"
         state: latest
         update_cache: yes
         force_apt_get: yes
       when: ansible_distribution == "Ubuntu"

     - name: Reboot hosts
       shell: 'reboot'
       ignore_errors: yes

     - name: Waiting for server to come back
       become: false
       local_action: wait_for host= {{ inventory_hostname }} port=22
                     search_regex=OpenSSH state=started delay=5

